### ISSUE TITLE
Show an error to the user when browser is not supported

### ISSUE THREAD

**Issue by jessmartin** [fission-codes/webnative-app-template#20]
## Motivation

We want this application to have good UX and suggest to developers the UX they should implement for their end-users. To that end, we want good error messages when they are needed.

## Finish Line

- [x] When the user has an unsupported browser or lack of certificate (`InsecureContext` or `UnsupportedBrowser`) we should display a helpful message to the user.

**Comment by jessmartin** [comment]
@depatchedmode we may need design support for this one as it's not in the mockup. We'll give it a crack and let ya know.

**Comment by bgins** [comment]
Completed in #24.
