### ISSUE TITLE
Implement storage

### ISSUE THREAD

**Issue by bgins** [fission-codes/webnative-app-template#5]
Add WNFS support to provide storage.

**Comment by jessmartin** [comment]
@bgins remind me what this issue actually is? 😂 

How does it differ from #3? Will there be any change to the UI that I can reference in the mockup?

**Comment by bgins** [comment]
This issue overlaps with #3 to some degree in the sense that we needed storage to upload images.

We have mostly completed the work for this issue, but we should consider refactoring the app to separate auth and storage into separate modules.

**Comment by jessmartin** [comment]
We reviewed the code and it feels well-factored enough. Closing this.
